# Generated by Django 6.0.4 on 2026-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_breakdown_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workorder",
            name="execution_workflow",
            field=models.BooleanField(
                default=True,
                help_text="When true, inventory moves only after production approval and store receipt.",
            ),
        ),
    ]
