# Generated by Django 6.0.4 on 2026-06-10 11:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_expand_sales_module"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.CharField(default="Tanzania", max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mine_type",
            field=models.CharField(
                choices=[
                    ("UNDERGROUND", "Underground"),
                    ("OPEN_PIT", "Open Pit"),
                    ("BOTH", "Both"),
                ],
                default="UNDERGROUND",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("IMMEDIATE", "Immediate"),
                    ("NET_15", "Net 15"),
                    ("NET_30", "Net 30"),
                    ("NET_60", "Net 60"),
                ],
                default="NET_30",
                max_length=20,
            ),
        ),
    ]
