# Generated by Django 6.0.4 on 2026-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("ASSET", "Asset"),
                    ("LIABILITY", "Liability"),
                    ("EQUITY", "Equity"),
                    ("REVENUE", "Revenue"),
                    ("EXPENSE", "Expense"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bankreconciliation",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("COMPLETED", "Completed")],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="period",
            field=models.CharField(
                choices=[
                    ("MONTHLY", "Monthly"),
                    ("QUARTERLY", "Quarterly"),
                    ("ANNUAL", "Annual"),
                ],
                default="ANNUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="reference_type",
            field=models.CharField(
                choices=[
                    ("INVOICE", "Invoice"),
                    ("PAYMENT", "Payment"),
                    ("PAYROLL", "Payroll"),
                    ("MANUAL", "Manual"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("POSTED", "Posted"),
                    ("REVERSED", "Reversed"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taxsetting",
            name="applicable_to",
            field=models.CharField(
                choices=[
                    ("SALES", "Sales"),
                    ("PURCHASE", "Purchase"),
                    ("PAYROLL", "Payroll"),
                ],
                max_length=20,
            ),
        ),
    ]
