# Generated by Django 6.0.4 on 2026-06-11 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hr", "0002_alter_allowanceconfig_department_and_more"),
        ("inventory", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PPERoleRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("job_title", models.CharField(max_length=150)),
                ("required_ppe_types", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["job_title"],
            },
        ),
        migrations.CreateModel(
            name="PPEItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "ppe_type",
                    models.CharField(
                        choices=[
                            ("HELMET", "Helmet"),
                            ("GLOVES", "Gloves"),
                            ("SAFETY_BOOTS", "Safety Boots"),
                            ("VEST", "Vest"),
                            ("GOGGLES", "Goggles"),
                            ("EAR_PROTECTION", "Ear Protection"),
                            ("HARNESS", "Harness"),
                            ("RESPIRATOR", "Respirator"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("safety_standard", models.CharField(blank=True, max_length=100)),
                ("total_issued", models.PositiveIntegerField(default=0)),
                ("stock_on_hand", models.PositiveIntegerField(default=0)),
                ("reorder_level", models.PositiveIntegerField(default=10)),
                (
                    "inventory_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_items",
                        to="inventory.item",
                    ),
                ),
            ],
            options={
                "ordering": ["ppe_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="PPEIssuance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                ("expected_return", models.DateField(blank=True, null=True)),
                ("actual_return", models.DateField(blank=True, null=True)),
                (
                    "condition_issued",
                    models.CharField(
                        choices=[("NEW", "New"), ("GOOD", "Good"), ("FAIR", "Fair")],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                (
                    "condition_returned",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ppe_issuances",
                        to="hr.employee",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ppe_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ppe_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="issuances",
                        to="safety.ppeitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="SafetyIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "incident_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("ACCIDENT", "Accident"),
                            ("NEAR_MISS", "Near Miss"),
                            ("DANGEROUS_OCCURRENCE", "Dangerous Occurrence"),
                            ("PROPERTY_DAMAGE", "Property Damage"),
                            ("ENVIRONMENTAL", "Environmental"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_occurred", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("immediate_actions", models.TextField(blank=True)),
                ("anyone_injured", models.BooleanField(default=False)),
                ("injury_description", models.TextField(blank=True)),
                ("body_parts", models.JSONField(blank=True, default=list)),
                ("medical_treatment_required", models.BooleanField(default=False)),
                ("hospitalized", models.BooleanField(default=False)),
                ("first_aid_given", models.BooleanField(default=False)),
                ("first_aid_provider", models.CharField(blank=True, max_length=150)),
                ("photos", models.JSONField(blank=True, default=list)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("cctv_reference", models.CharField(blank=True, max_length=255)),
                ("immediate_cause", models.TextField(blank=True)),
                ("contributing_factors", models.JSONField(blank=True, default=list)),
                ("root_cause", models.TextField(blank=True)),
                ("root_cause_categories", models.JSONField(blank=True, default=list)),
                ("why_analysis", models.JSONField(blank=True, default=list)),
                ("investigation_findings", models.TextField(blank=True)),
                ("investigated_at", models.DateTimeField(blank=True, null=True)),
                ("lessons_learned", models.TextField(blank=True)),
                ("prevention_measures", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="safety_incidents",
                        to="users.department",
                    ),
                ),
                (
                    "injured_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="injury_incidents",
                        to="hr.employee",
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents_investigated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents_reported",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_occurred"],
            },
        ),
        migrations.CreateModel(
            name="IncidentWitness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("is_employee", models.BooleanField(default=False)),
                ("contact", models.CharField(blank=True, max_length=100)),
                ("statement", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hr.employee",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="witnesses",
                        to="safety.safetyincident",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "inspection_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                            ("SPECIAL", "Special"),
                            ("REGULATORY", "Regulatory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(max_length=100)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "overall_result",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PASS", "Pass"),
                            ("FAIL", "Fail"),
                            ("CONDITIONAL", "Conditional"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("passed_items", models.PositiveIntegerField(default=0)),
                ("failed_items", models.PositiveIntegerField(default=0)),
                ("next_inspection", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "inspector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inspections_conducted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="InspectionChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("section", models.CharField(max_length=100)),
                ("checklist_item", models.CharField(max_length=255)),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("PASS", "Pass"), ("FAIL", "Fail"), ("NA", "N/A")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("photo_url", models.CharField(blank=True, max_length=500)),
                (
                    "inspection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="safety.safetyinspection",
                    ),
                ),
            ],
            options={
                "ordering": ["section", "id"],
            },
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("action", models.TextField()),
                ("due_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrective_actions_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="safety.safetyincident",
                    ),
                ),
                (
                    "inspection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrective_actions",
                        to="safety.safetyinspection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SafetyTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("training_name", models.CharField(max_length=255)),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("INDUCTION", "Induction"),
                            ("REFRESHER", "Refresher"),
                            ("SPECIFIC", "Specific"),
                            ("EMERGENCY", "Emergency"),
                            ("REGULATORY", "Regulatory"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("trainer", models.CharField(max_length=150)),
                ("scheduled_date", models.DateTimeField()),
                (
                    "duration_hours",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                ("location", models.CharField(blank=True, max_length=150)),
                ("max_attendees", models.PositiveIntegerField(default=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("materials_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainings_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="WorkPermit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "permit_number",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "permit_type",
                    models.CharField(
                        choices=[
                            ("HOT_WORK", "Hot Work"),
                            ("CONFINED_SPACE", "Confined Space"),
                            ("ELECTRICAL", "Electrical"),
                            ("HEIGHT_WORK", "Height Work"),
                            ("EXCAVATION", "Excavation"),
                            ("CHEMICAL", "Chemical"),
                            ("GENERAL", "General"),
                        ],
                        max_length=30,
                    ),
                ),
                ("work_description", models.TextField()),
                ("location", models.CharField(max_length=100)),
                ("workers", models.JSONField(blank=True, default=list)),
                ("equipment_tools", models.TextField(blank=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("hazards", models.JSONField(blank=True, default=list)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("control_measures", models.TextField()),
                ("safety_checklist", models.JSONField(blank=True, default=list)),
                ("extension_count", models.PositiveSmallIntegerField(default=0)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="permits_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="work_permits",
                        to="users.department",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="permits_issued",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("attended", models.BooleanField(default=False)),
                ("certificate_issued", models.BooleanField(default=False)),
                ("certificate_expiry", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_attendance",
                        to="hr.employee",
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="safety.safetytraining",
                    ),
                ),
            ],
            options={
                "unique_together": {("training", "employee")},
            },
        ),
    ]
