# Generated by Django 6.0.4 on 2026-06-11 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_allowanceconfig_department_and_more'),
        ('procurement', '0001_initial'),
        ('safety', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PPERequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('request_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_STORE', 'Pending Store Review'), ('AVAILABLE', 'Stock Available'), ('IN_PROCUREMENT', 'In Procurement'), ('STOCK_RECEIVED', 'Stock Received'), ('READY_FOR_ISSUE', 'Ready for Issue'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('store_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('store_notes', models.TextField(blank=True)),
                ('stock_available', models.BooleanField(blank=True, null=True)),
                ('procurement_notes', models.TextField(blank=True)),
                ('stock_received_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_requests', to='hr.employee')),
                ('issuance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='safety.ppeissuance')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='safety.ppeitem')),
                ('purchase_requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_requests', to='procurement.purchaserequisition')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ppe_requests_created', to=settings.AUTH_USER_MODEL)),
                ('stock_received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_requests_stock_received', to=settings.AUTH_USER_MODEL)),
                ('store_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppe_requests_store_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ppeissuance',
            name='ppe_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='safety.pperequest'),
        ),
    ]
