# Generated by Django 6.0.4 on 2026-06-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safety', '0002_pperequest_ppeissuance_ppe_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='pperequest',
            name='requested_new_item',
            field=models.BooleanField(default=False, help_text='True when Safety Officer requested an item not previously in stock'),
        ),
        migrations.AlterField(
            model_name='ppeitem',
            name='ppe_type',
            field=models.CharField(choices=[('HELMET', 'Helmet'), ('GLOVES', 'Gloves'), ('SAFETY_BOOTS', 'Safety Boots'), ('VEST', 'Vest'), ('GOGGLES', 'Goggles'), ('EAR_PROTECTION', 'Ear Protection'), ('HARNESS', 'Harness'), ('RESPIRATOR', 'Respirator'), ('UNIFORM', 'Uniform / Workwear'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
