# Generated by Django 6.0.4 on 2026-06-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_theme_default_light"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="module",
            field=models.CharField(
                choices=[
                    ("inventory", "Inventory"),
                    ("procurement", "Procurement"),
                    ("sales", "Sales"),
                    ("logistics", "Logistics"),
                    ("driver_portal", "Driver Portal"),
                    ("production", "Production"),
                    ("finance", "Finance"),
                    ("hr", "HR"),
                    ("safety", "Safety"),
                    ("messaging", "Messaging"),
                    ("email", "Email"),
                    ("users", "Users"),
                    ("settings", "Settings"),
                ],
                max_length=50,
            ),
        ),
    ]
