# Generated by Django 6.0.4 on 2026-06-14 13:11

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_internal_consumption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departmentrequestline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Requested quantity (legacy field, mirrors requested_qty).",
                max_digits=18,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0001"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="goodsissuenote",
            name="department",
            field=models.CharField(
                choices=[
                    ("PRODUCTION", "Production"),
                    ("MAINTENANCE", "Maintenance"),
                    ("HSE", "HSE"),
                    ("LOGISTICS", "Logistics"),
                    ("SALES", "Sales"),
                    ("PROCUREMENT", "Procurement"),
                    ("ADMINISTRATION", "Administration"),
                ],
                max_length=30,
            ),
        ),
    ]
