# Generated manually for HR module

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("days_entitled", models.PositiveIntegerField(default=0)),
                ("is_paid", models.BooleanField(default=True)),
                ("carry_forward", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("company_name", models.CharField(default="Rock Solutions Limited", max_length=255)),
                ("tin", models.CharField(default="127-950-695", max_length=50)),
                ("vat_number", models.CharField(default="40022138R", max_length=50)),
                ("address", models.TextField(default="Plot 252 Block L, Misungwi, Mwanza")),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("logo_url", models.CharField(blank=True, max_length=500)),
            ],
            options={"verbose_name": "Company Profile"},
        ),
        migrations.CreateModel(
            name="WorkingHoursConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("hours_per_day", models.DecimalField(decimal_places=2, default=Decimal("8"), max_digits=4)),
                ("working_days", models.CharField(default="MON,TUE,WED,THU,FRI", max_length=50)),
            ],
            options={"verbose_name": "Working Hours Configuration"},
        ),
        migrations.CreateModel(
            name="AllowanceConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("is_taxable", models.BooleanField(default=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="allowance_configs", to="users.department")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("employee_number", models.CharField(editable=False, max_length=30, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("gender", models.CharField(default="MALE", max_length=10)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("national_id", models.CharField(blank=True, max_length=50)),
                ("tin_number", models.CharField(blank=True, max_length=50)),
                ("nssf_number", models.CharField(blank=True, max_length=50)),
                ("nhif_number", models.CharField(blank=True, max_length=50)),
                ("paye_applicable", models.BooleanField(default=True)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("work_email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("profile_photo", models.CharField(blank=True, max_length=500)),
                ("job_title", models.CharField(max_length=150)),
                ("employment_type", models.CharField(default="PERMANENT", max_length=20)),
                ("contract_start", models.DateField(blank=True, null=True)),
                ("contract_end", models.DateField(blank=True, null=True)),
                ("probation_end", models.DateField(blank=True, null=True)),
                ("basic_salary", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("payment_frequency", models.CharField(default="MONTHLY", max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("bank_account_name", models.CharField(blank=True, max_length=255)),
                ("bank_branch", models.CharField(blank=True, max_length=100)),
                ("emergency_contact_name", models.CharField(blank=True, max_length=150)),
                ("emergency_contact_relationship", models.CharField(blank=True, max_length=50)),
                ("emergency_contact_phone", models.CharField(blank=True, max_length=30)),
                ("emergency_contact_address", models.TextField(blank=True)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("create_user_account", models.BooleanField(default=False)),
                ("resignation_date", models.DateField(blank=True, null=True)),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employees", to="core.currency")),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employees", to="users.department")),
                ("reports_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="direct_reports", to="hr.employee")),
                ("user", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="employee_profile", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["employee_number"]},
        ),
        migrations.CreateModel(
            name="Payroll",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("payroll_number", models.CharField(editable=False, max_length=30, unique=True)),
                ("period_month", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ("period_year", models.PositiveIntegerField()),
                ("total_employees", models.PositiveIntegerField(default=0)),
                ("total_gross", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_nssf_employee", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_nssf_employer", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_paye", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_nhif", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_net", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("status", models.CharField(default="DRAFT", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payrolls_approved", to=settings.AUTH_USER_MODEL)),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payrolls", to="users.department")),
                ("processed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="payrolls_processed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-period_year", "-period_month"], "unique_together": {("period_month", "period_year", "department")}},
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=150)),
                ("date", models.DateField()),
                ("is_variable", models.BooleanField(default=False)),
                ("year", models.PositiveIntegerField()),
            ],
            options={"ordering": ["date"], "unique_together": {("name", "year")}},
        ),
        migrations.CreateModel(
            name="PayrollItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("basic_salary", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("allowances_json", models.JSONField(blank=True, default=list)),
                ("total_allowances", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("gross_salary", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("nssf_employee", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("nssf_employer", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("paye", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("nhif", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("other_deductions", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_deductions", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("net_salary", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_items", to="hr.employee")),
                ("payroll", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="hr.payroll")),
            ],
            options={"ordering": ["employee__employee_number"], "unique_together": {("payroll", "employee")}},
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("days_requested", models.PositiveIntegerField(default=1)),
                ("reason", models.TextField(blank=True)),
                ("medical_certificate", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="leave_approved", to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_requests", to="hr.employee")),
                ("leave_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="hr.leavetype")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("doc_type", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=255)),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_expired", models.BooleanField(default=False)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="hr.employee")),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAllowance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("is_taxable", models.BooleanField(default=True)),
                ("effective_date", models.DateField(default=django.utils.timezone.now)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allowances", to="hr.employee")),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DisciplinaryRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("incident_date", models.DateField()),
                ("record_type", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("action_taken", models.TextField(blank=True)),
                ("witness", models.CharField(blank=True, max_length=150)),
                ("employee_acknowledged", models.BooleanField(default=False)),
                ("is_confidential", models.BooleanField(default=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="disciplinary_records", to="hr.employee")),
                ("issued_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="disciplinary_issued", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-incident_date"]},
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("date", models.DateField()),
                ("time_in", models.TimeField(blank=True, null=True)),
                ("time_out", models.TimeField(blank=True, null=True)),
                ("hours_worked", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5)),
                ("status", models.CharField(default="PRESENT", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attendance_records", to="hr.employee")),
                ("marked_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="attendance_marked", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-date"], "unique_together": {("employee", "date")}},
        ),
        migrations.CreateModel(
            name="Appraisal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("period", models.CharField(default="ANNUAL", max_length=20)),
                ("period_label", models.CharField(blank=True, max_length=100)),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ("rating", models.CharField(blank=True, max_length=30)),
                ("strengths", models.TextField(blank=True)),
                ("improvements", models.TextField(blank=True)),
                ("goals", models.TextField(blank=True)),
                ("comments", models.TextField(blank=True)),
                ("employee_acknowledged", models.BooleanField(default=False)),
                ("status", models.CharField(default="SCHEDULED", max_length=20)),
                ("scheduled_date", models.DateField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appraisals", to="hr.employee")),
                ("reviewer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="appraisals_reviewed", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-scheduled_date"]},
        ),
    ]
