# Generated by Django 6.0.4 on 2026-06-11 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowanceconfig",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Null = applies to all departments",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allowance_configs",
                to="users.department",
            ),
        ),
        migrations.AlterField(
            model_name="appraisal",
            name="period",
            field=models.CharField(
                choices=[("QUARTER", "Quarter"), ("ANNUAL", "Annual")],
                default="ANNUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="appraisal",
            name="status",
            field=models.CharField(
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("PRESENT", "Present"),
                    ("ABSENT", "Absent"),
                    ("LATE", "Late"),
                    ("HALF_DAY", "Half Day"),
                    ("LEAVE", "Leave"),
                ],
                default="PRESENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="disciplinaryrecord",
            name="record_type",
            field=models.CharField(
                choices=[
                    ("VERBAL_WARNING", "Verbal Warning"),
                    ("WRITTEN_WARNING", "Written Warning"),
                    ("FINAL_WARNING", "Final Warning"),
                    ("SUSPENSION", "Suspension"),
                    ("TERMINATION", "Termination"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("PERMANENT", "Permanent"),
                    ("CONTRACT", "Contract"),
                    ("CASUAL", "Casual"),
                ],
                default="PERMANENT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Male"), ("FEMALE", "Female")],
                default="MALE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="payment_frequency",
            field=models.CharField(
                choices=[("MONTHLY", "Monthly"), ("WEEKLY", "Weekly")],
                default="MONTHLY",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("ACTIVE", "Active"),
                    ("INACTIVE", "Inactive"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="employeedocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("CONTRACT", "Contract"),
                    ("NIN", "National ID"),
                    ("CERTIFICATE", "Certificate"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REVIEWED", "Reviewed"),
                    ("APPROVED", "Approved"),
                    ("PAID", "Paid"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
    ]
