"""
Jazzmin admin theme configuration for Rock Solutions FMS.

Docs: https://django-jazzmin.readthedocs.io/
"""

import os

_FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:4200").strip()

JAZZMIN_SETTINGS = {
    "site_title": "Rock Solutions FMS",
    "site_header": "Rock Solutions FMS",
    "site_brand": "Rock Solutions",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Rock Solutions Limited — FMS Administration",
    "copyright": "Rock Solutions Limited",
    "search_model": [
        "users.User",
        "inventory.Item",
        "sales.Customer",
        "procurement.Supplier",
    ],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "FMS API", "url": "/api/v1/core/", "new_window": False},
        {"name": "Frontend", "url": _FRONTEND_URL, "new_window": True},
        {"model": "users.User"},
    ],
    "usermenu_links": [
        {"name": "FMS Frontend", "url": _FRONTEND_URL, "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": [
        "users",
        "inventory",
        "procurement",
        "sales",
        "logistics",
        "production",
        "finance",
        "hr",
        "safety",
        "messaging",
        "email_client",
        "core",
        "auth",
    ],
    "custom_links": {
        "inventory": [
            {
                "name": "Inventory API",
                "url": "/api/v1/inventory/",
                "icon": "fas fa-boxes",
                "permissions": ["inventory.view_item"],
            }
        ],
    },
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        "users": "fas fa-user-shield",
        "users.user": "fas fa-user",
        "users.role": "fas fa-user-tag",
        "core": "fas fa-cog",
        "core.currency": "fas fa-coins",
        "inventory": "fas fa-warehouse",
        "inventory.item": "fas fa-box",
        "inventory.itemcategory": "fas fa-tags",
        "inventory.warehouse": "fas fa-building",
        "inventory.stock": "fas fa-cubes",
        "inventory.stockmovement": "fas fa-exchange-alt",
        "inventory.stockadjustment": "fas fa-sliders-h",
        "inventory.stockbatch": "fas fa-layer-group",
        "inventory.stocktransfer": "fas fa-truck-loading",
        "inventory.departmentrequest": "fas fa-clipboard-list",
        "inventory.goodsissuenote": "fas fa-file-export",
        "inventory.stocktake": "fas fa-clipboard-check",
        "procurement": "fas fa-shopping-cart",
        "procurement.supplier": "fas fa-truck",
        "procurement.purchaserequisition": "fas fa-file-alt",
        "procurement.purchaseorder": "fas fa-file-invoice",
        "sales": "fas fa-chart-line",
        "sales.customer": "fas fa-handshake",
        "sales.salesorder": "fas fa-receipt",
        "logistics": "fas fa-shipping-fast",
        "logistics.vehicle": "fas fa-truck",
        "logistics.deliveryorder": "fas fa-route",
        "production": "fas fa-industry",
        "production.product": "fas fa-th",
        "production.billofmaterials": "fas fa-list-ul",
        "production.workorder": "fas fa-tasks",
        "finance": "fas fa-calculator",
        "finance.account": "fas fa-book",
        "finance.journalentry": "fas fa-journal-whills",
        "hr": "fas fa-id-badge",
        "hr.employee": "fas fa-user-tie",
        "hr.payroll": "fas fa-money-check-alt",
        "safety": "fas fa-hard-hat",
        "safety.safetyincident": "fas fa-exclamation-triangle",
        "messaging": "fas fa-comments",
        "email_client": "fas fa-envelope",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "users.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": False,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-warning",
    "navbar": "navbar-dark navbar-primary",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}
