# Generated by Django 6.0.4 on 2026-06-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('imap_host', models.CharField(default='mail.rocksolutions.co.tz', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(default='mail.rocksolutions.co.tz', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password_encrypted', models.TextField(blank=True)),
                ('sync_frequency', models.PositiveIntegerField(default=5)),
                ('sync_days', models.PositiveIntegerField(default=30)),
                ('max_per_sync', models.PositiveIntegerField(default=50)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['email_address'],
            },
        ),
        migrations.CreateModel(
            name='EmailLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_labels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=10)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=255)),
                ('to_addresses', models.JSONField(default=list)),
                ('cc_addresses', models.JSONField(blank=True, default=list)),
                ('bcc_addresses', models.JSONField(blank=True, default=list)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('folder', models.CharField(choices=[('INBOX', 'Inbox'), ('SENT', 'Sent'), ('DRAFT', 'Draft'), ('TRASH', 'Trash'), ('SPAM', 'Spam')], default='INBOX', max_length=20)),
                ('thread_id', models.CharField(blank=True, max_length=255, null=True)),
                ('has_attachments', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField()),
                ('linked_customer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('linked_supplier_id', models.PositiveIntegerField(blank=True, null=True)),
                ('email_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_client.emailaccount')),
                ('labels', models.ManyToManyField(blank=True, related_name='emails', to='email_client.emaillabel')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_client.emailmessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
